# Site settings
title: Musings On Data
author: Clint Howard
header-img: img/home-bg.jpg
email: clintshoward@gmail.com
copyright_name:
description: "Personal website for Clint Howard"
baseurl: ""
url: "https://clinthoward.github.io"
twitter_username:
github_username:  clinthoward
facebook_username:
email_username:  clintshoward@gmail.com
linkedin_username: clint-howard

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
#google_tracking_id: UA-85406922-1
google_analytics: G-RN281GHWK6

author :
  name : Clint Howard
  email : clintshoward@gmail.com
  github : clinthoward
  linkedin: clint-howard

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

layout: default
comments: true
